import { patchScale } from '../sizeUtils';

/**
 ** Tokens that don't require palette
 **/

const space = {
  'space-0': '0',
  'space-1': patchScale(1),
  'space-2': patchScale(2),
  'space-3': patchScale(3),
  'space-4': patchScale(4),
  'space-5': patchScale(5),
  'space-6': patchScale(6),
  'space-7': patchScale(7),
  'space-8': patchScale(8),
  'space-9': patchScale(9),
  'space-10': patchScale(10),
  'space-11': patchScale(11),
  'space-12': patchScale(12),
  'space-13': patchScale(13),
  'space-14': patchScale(14),
  'space-15': patchScale(15),
  'space-16': patchScale(16),
  'space-17': patchScale(17),
  'space-18': patchScale(18),
  'space-19': patchScale(19),
  'space-20': patchScale(20),

  'space-negative-1': patchScale(1, { destructive: true }),
  'space-negative-2': patchScale(2, { destructive: true }),
  'space-negative-3': patchScale(3, { destructive: true }),
  'space-negative-4': patchScale(4, { destructive: true }),
  'space-negative-5': patchScale(5, { destructive: true }),
  'space-negative-6': patchScale(6, { destructive: true }),
  'space-negative-7': patchScale(7, { destructive: true }),
  'space-negative-8': patchScale(8, { destructive: true }),
  'space-negative-9': patchScale(9, { destructive: true }),
  'space-negative-10': patchScale(10, { destructive: true }),
  'space-negative-11': patchScale(11, { destructive: true }),
  'space-negative-12': patchScale(12, { destructive: true }),
  'space-negative-13': patchScale(13, { destructive: true }),
  'space-negative-14': patchScale(14, { destructive: true }),
  'space-negative-15': patchScale(15, { destructive: true }),
  'space-negative-16': patchScale(16, { destructive: true }),
  'space-negative-17': patchScale(17, { destructive: true }),
  'space-negative-18': patchScale(18, { destructive: true }),
  'space-negative-19': patchScale(19, { destructive: true }),
  'space-negative-20': patchScale(20, { destructive: true }),

  xxs: patchScale(1),
  xs: patchScale(2),
  sm: patchScale(4),
  md: patchScale(8),
  lg: patchScale(16),
  xl: patchScale(32),
  xxl: patchScale(64),
};

const sizes = {
  'size-0': '0',
  'size-1': patchScale(1),
  'size-2': patchScale(2),
  'size-3': patchScale(3),
  'size-4': patchScale(4),
  'size-5': patchScale(5),
  'size-6': patchScale(6),
  'size-7': patchScale(7),
  'size-8': patchScale(8),
  'size-9': patchScale(9),
  'size-10': patchScale(10),
  'size-11': patchScale(11),
  'size-12': patchScale(12),
  'size-13': patchScale(13),
  'size-14': patchScale(14),
  'size-15': patchScale(15),
  'size-16': patchScale(16),
  'size-17': patchScale(17),
  'size-18': patchScale(18),
  'size-19': patchScale(19),
  'size-20': patchScale(20),
  'size-21': patchScale(21),
  'size-22': patchScale(22),
  'size-23': patchScale(23),
  'size-24': patchScale(24),
  'size-25': patchScale(25),
  'size-26': patchScale(26),
  'size-27': patchScale(27),
  'size-28': patchScale(28),
  'size-29': patchScale(29),
  'size-30': patchScale(30),

  /** should match fontSizes */
  'icon-xxs': patchScale(5),
  'icon-xs': patchScale(7),
  'icon-sm': patchScale(8),
  'icon-md': patchScale(10),
  'icon-lg': patchScale(12),
  'icon-xl': patchScale(13),
  'icon-xxl': patchScale(15),
  'spinner-xxs': patchScale(5),
  'spinner-xs': patchScale(7),
  'spinner-sm': patchScale(8),
  'spinner-md': patchScale(10),
  'spinner-lg': patchScale(12),
  'spinner-xl': patchScale(13),
  'spinner-xxl': patchScale(15),

  max: 'max-content',
  min: 'min-content',
  full: '100%',
};

const zIndices = {
  hide: -1,
  auto: 'auto',
  base: 0,
  docked: 10,
  dropdown: 1000,
  sticky: 1100,
  banner: 1200,
  overlay: 1300,
  dialog: 1400,
  popover: 1500,
  skipLink: 1600,
  toast: 1700,
  tooltip: 1800,
};

const radii = {
  none: 0,
  xxs: '0.5px',
  xs: '0.75px',
  sm: patchScale(1),
  md: patchScale(2),
  lg: patchScale(4),
  xl: patchScale(5),
  xxl: patchScale(6),
  interactive: patchScale(2),
  layer: patchScale(2),
  squarish: '1px',
  circle: '50%',
};

/** @todo add font-size-0 */
const fontSizes = {
  'font-size-1': patchScale(5),
  'font-size-2': patchScale(6),
  'font-size-3': patchScale(7),
  'font-size-4': patchScale(9),
  'font-size-5': patchScale(11),
  'font-size-6': patchScale(13),
  'font-size-7': patchScale(15),
  'font-size-8': patchScale(17),
  'font-size-9': patchScale(19),
  'font-size-10': patchScale(21),
  'font-size-11': patchScale(23),
  'rem-base': '0.625rem',
  body: patchScale(6),
  button: patchScale(6),
  'button-sm': patchScale(6),
  'button-lg': patchScale(7),
  badge: patchScale(6),
  label: patchScale(6),
  h1: patchScale(17),
  h2: patchScale(13),
  h3: patchScale(11),
  h4: patchScale(9),
  h5: patchScale(7),
  h6: patchScale(6),
};

const fontWeights = {
  thin: 300,
  light: 400,
  regular: 400,
  medium: 500,
  'semi-bold': 600,
  bold: 700,
};

const letterSpacings = {
  none: '0',
  xxs: '0.05px',
  xs: '0.1px',
  sm: '0.25px',
  md: '0.3px',
  lg: '0.5px',
  xl: '0.5px',
  xxl: '0.5px',
  body: '0.25px',
  heading: '0.3px',
  mono: '0.3px',
  code: '0.3px',
};

const lineHeights = {
  'line-height-1': patchScale(5),
  'line-height-2': patchScale(6),
  'line-height-3': patchScale(7),
  'line-height-4': patchScale(9),
  'line-height-5': patchScale(11),
  'line-height-6': patchScale(13),
  'line-height-7': patchScale(15),
  'line-height-8': patchScale(17),
  'line-height-9': patchScale(19),
  'line-height-10': patchScale(21),
  'line-height-11': patchScale(23),
  normal: 'normal',
  body: patchScale(6),
  button: patchScale(6),
  'button-sm': patchScale(6),
  'button-lg': patchScale(7),
  badge: patchScale(6),
  label: patchScale(6),
  h1: patchScale(17),
  h2: patchScale(13),
  h3: patchScale(11),
  h4: patchScale(9),
  h5: patchScale(7),
  h6: patchScale(6),
};

const defaultFontFamily =
  '-apple-system,BlinkMacSystemFont,"Segoe UI","Roboto","Oxygen","Ubuntu","Cantarell","Fira Sans","Droid Sans","Helvetica Neue",sans-serif';
const monoFontFamily =
  'SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace';

const fonts = {
  heading: defaultFontFamily,
  body: defaultFontFamily,
  mono: monoFontFamily,
  code: monoFontFamily,
};

const borderWidths = {
  none: 0,
  md: '1px',
  lg: '2px',
  'border-width-3': '3px',
  xl: '4px',
  'border-width-5': '5px',
  'border-width-6': '6px',
  'border-width-7': '7px',
  xxl: '8px',
  'border-width-9': '9px',
  'border-width-10': '10px',
  xxs: '0.125px',
  xs: '0.25px',
  sm: '0.5',
};

export {
  borderWidths,
  fonts,
  fontSizes,
  fontWeights,
  letterSpacings,
  lineHeights,
  radii,
  sizes,
  space,
  zIndices,
};
