export type {
  SelectArrowProps as AriakitSelectArrowProps,
  SelectGroupLabelProps as AriakitSelectGroupLabelProps,
  SelectGroupProps as AriakitSelectGroupProps,
  SelectItemProps as AriakitSelectItemProps,
  SelectLabelProps as AriakitSelectLabelProps,
  SelectPopoverProps as AriakitSelectPopoverProps,
  SelectProviderProps as AriakitSelectProviderProps,
  SelectSeparatorProps as AriakitSelectSeparatorProps,
} from '@ariakit/react/select';
export {
  Select as AriakitSelect,
  SelectArrow as AriakitSelectArrow,
  SelectGroup as AriakitSelectGroup,
  SelectGroupLabel as AriakitSelectGroupLabel,
  SelectItem as AriakitSelectItem,
  SelectLabel as AriakitSelectLabel,
  SelectPopover as AriakitSelectPopover,
  SelectProvider as AriakitSelectProvider,
  SelectSeparator as AriakitSelectSeparator,
} from '@ariakit/react/select';
