export type {
  AriakitPopoverArrowProps as SelectArrowPrimitiveProps,
  AriakitSelectGroupLabelProps as SelectGroupLabelPrimitiveProps,
  AriakitSelectGroupProps as SelectGroupPrimitiveProps,
  AriakitSelectItemProps as SelectItemPrimitiveProps,
  AriakitSelectPopoverProps as SelectPopoverPrimitiveProps,
  AriakitSelectProviderProps as SelectProviderPrimitiveProps,
  AriakitSelectSeparatorProps as SelectSeparatorPrimitiveProps,
} from '@real-system/ariakit-library';
export {
  AriakitPopoverArrow as SelectArrowPrimitive,
  AriakitSelectGroupLabel as SelectGroupLabelPrimitive,
  AriakitSelectGroup as SelectGroupPrimitive,
  AriakitSelectItem as SelectItemPrimitive,
  AriakitSelectLabel as SelectLabelPrimitive,
  AriakitSelectPopover as SelectPopoverPrimitive,
  AriakitSelect as SelectPrimitive,
  AriakitSelectProvider as SelectProviderPrimitive,
  AriakitSelectSeparator as SelectSeparatorPrimitive,
} from '@real-system/ariakit-library';
