import { patchScale } from '../sizeUtils';

/**
 ** Tokens that don't require palette
 **/

const space = {
  'space-0': '0',
  'space-1': patchScale(1),
  'space-2': patchScale(2),
  'space-3': patchScale(3),
  'space-4': patchScale(4),
  'space-5': patchScale(5),
  'space-6': patchScale(6),
  'space-7': patchScale(7),
  'space-8': patchScale(8),
  'space-9': patchScale(9),
  'space-10': patchScale(10),
  'space-11': patchScale(11),
  'space-12': patchScale(12),
  'space-13': patchScale(13),
  'space-14': patchScale(14),
  'space-15': patchScale(15),
  'space-16': patchScale(16),
  'space-17': patchScale(17),
  'space-18': patchScale(18),
  'space-19': patchScale(19),
  'space-20': patchScale(20),

  'space-negative-1': patchScale(1, { destructive: true }),
  'space-negative-2': patchScale(2, { destructive: true }),
  'space-negative-3': patchScale(3, { destructive: true }),
  'space-negative-4': patchScale(4, { destructive: true }),
  'space-negative-5': patchScale(5, { destructive: true }),
  'space-negative-6': patchScale(6, { destructive: true }),
  'space-negative-7': patchScale(7, { destructive: true }),
  'space-negative-8': patchScale(8, { destructive: true }),
  'space-negative-9': patchScale(9, { destructive: true }),
  'space-negative-10': patchScale(10, { destructive: true }),
  'space-negative-11': patchScale(11, { destructive: true }),
  'space-negative-12': patchScale(12, { destructive: true }),
  'space-negative-13': patchScale(13, { destructive: true }),
  'space-negative-14': patchScale(14, { destructive: true }),
  'space-negative-15': patchScale(15, { destructive: true }),
  'space-negative-16': patchScale(16, { destructive: true }),
  'space-negative-17': patchScale(17, { destructive: true }),
  'space-negative-18': patchScale(18, { destructive: true }),
  'space-negative-19': patchScale(19, { destructive: true }),
  'space-negative-20': patchScale(20, { destructive: true }),
};

const sizes = {
  'size-0': '0',
  'size-1': patchScale(1),
  'size-2': patchScale(2),
  'size-3': patchScale(3),
  'size-4': patchScale(4),
  'size-5': patchScale(5),
  'size-6': patchScale(6),
  'size-7': patchScale(7),
  'size-8': patchScale(8),
  'size-9': patchScale(9),
  'size-10': patchScale(10),
  'size-11': patchScale(11),
  'size-12': patchScale(12),
  'size-13': patchScale(13),
  'size-14': patchScale(14),
  'size-15': patchScale(15),
  'size-16': patchScale(16),
  'size-17': patchScale(17),
  'size-18': patchScale(18),
  'size-19': patchScale(19),
  'size-20': patchScale(20),
  'size-21': patchScale(21),
  'size-22': patchScale(22),
  'size-23': patchScale(23),
  'size-24': patchScale(24),
  'size-25': patchScale(25),
  'size-26': patchScale(26),
  'size-27': patchScale(27),
  'size-28': patchScale(28),
  'size-29': patchScale(29),
  'size-30': patchScale(30),

  // should match fontSizes
  'icon-1': patchScale(5),
  'icon-2': patchScale(7),
  'icon-3': patchScale(8),
  'icon-4': patchScale(10),
  'icon-5': patchScale(12),
  'icon-6': patchScale(13),
  'icon-7': patchScale(15),

  'spinner-1': patchScale(5),
  'spinner-2': patchScale(7),
  'spinner-3': patchScale(8),
  'spinner-4': patchScale(10),
  'spinner-5': patchScale(12),
  'spinner-6': patchScale(13),
  'spinner-7': patchScale(15),

  max: 'max-content',
  min: 'min-content',
  full: '100%',
};

const zIndices = {
  'z-index-0': '0',
  'z-index-1': '10',
  'z-index-2': '20',
  'z-index-3': '30',
  'z-index-4': '40',
  'z-index-5': '50',
  'z-index-6': '60',
  'z-index-7': '70',
  'z-index-8': '80',
  'z-index-9': '90',
  hide: -1,
  auto: 'auto',
  base: 0,
  docked: 10,
  dropdown: 1000,
  sticky: 1100,
  banner: 1200,
  overlay: 1300,
  dialog: 1400,
  popover: 1500,
  skipLink: 1600,
  toast: 1700,
  tooltip: 1800,
};

const radii = {
  'border-radius-0': '0',
  'border-radius-1': patchScale(1),
  'border-radius-2': patchScale(2),
  'border-radius-3': patchScale(4),
  'border-radius-circle': '50%',
  interactive: patchScale(2),
  layer: patchScale(2),
  squarish: '1px',
  circle: '50%',
};

const letterSpacings = {
  'letter-spacing-0': '0',
  'letter-spacing-1': '0.05px',
  'letter-spacing-2': '0.1px',
  'letter-spacing-3': '0.25px',
  'letter-spacing-4': '0.3px',
  'letter-spacing-5': '0.5px',
  body: '0.25px',
  heading: '0.3px',
};

const fontWeights = {
  // 'font-weight-light': 400,
  'font-weight-normal': '400',
  'font-weight-medium': '500',
  'font-weight-semibold': '600',
  'font-weight-bold': '700',
};

/** @todo add font-size-0 */
const fontSizes = {
  'font-size-1': patchScale(5),
  'font-size-2': patchScale(6),
  'font-size-3': patchScale(7),
  'font-size-4': patchScale(9),
  'font-size-5': patchScale(11),
  'font-size-6': patchScale(13),
  'font-size-7': patchScale(15),
  'font-size-8': patchScale(17),
  'font-size-9': patchScale(19),
  'font-size-10': patchScale(21),
  'font-size-11': patchScale(23),
  'rem-base': '0.625rem',
  body: patchScale(6),
  button: patchScale(6),
  'button-sm': patchScale(6),
  'button-lg': patchScale(7),
  h1: patchScale(17),
  h2: patchScale(13),
  h3: patchScale(11),
  h4: patchScale(9),
  h5: patchScale(7),
  h6: patchScale(6),
};

const lineHeights = {
  'line-height-1': patchScale(5),
  'line-height-2': patchScale(6),
  'line-height-3': patchScale(7),
  'line-height-4': patchScale(9),
  'line-height-5': patchScale(11),
  'line-height-6': patchScale(13),
  'line-height-7': patchScale(15),
  'line-height-8': patchScale(17),
  'line-height-9': patchScale(19),
  'line-height-10': patchScale(21),
  'line-height-11': patchScale(23),
  normal: 'normal',
  body: patchScale(6),
  button: patchScale(6),
  'button-sm': patchScale(6),
  'button-lg': patchScale(7),
  h1: patchScale(17),
  h2: patchScale(13),
  h3: patchScale(11),
  h4: patchScale(9),
  h5: patchScale(7),
  h6: patchScale(6),
};

const fonts = {
  'font-family-text':
    '-apple-system,BlinkMacSystemFont,"Segoe UI","Roboto","Oxygen","Ubuntu","Cantarell","Fira Sans","Droid Sans","Helvetica Neue",sans-serif',
  'font-family-code': "'Fira Mono', 'Courier New', Courier, monospace",
  body: '-apple-system,BlinkMacSystemFont,"Segoe UI","Roboto","Oxygen","Ubuntu","Cantarell","Fira Sans","Droid Sans","Helvetica Neue",sans-serif',
  code: "'Fira Mono', 'Courier New', Courier, monospace",
};

const borderWidths = {
  'border-width-0': '0',
  'border-width-1': '1px',
  'border-width-2': '2px',
  'border-width-3': '3px',
  'border-width-4': '4px',
  'border-width-5': '5px',
  'border-width-6': '6px',
  'border-width-7': '7px',
  'border-width-8': '8px',
  'border-width-9': '9px',
  'border-width-10': '10px',
  none: 0,
  xxs: '0.125px',
  xs: '0.25px',
  sm: '0.5',
  md: '1px',
  lg: '4px',
  xl: '8px',
  xxl: '10px',
};
export {
  borderWidths,
  fonts,
  fontSizes,
  fontWeights,
  letterSpacings,
  lineHeights,
  radii,
  sizes,
  space,
  zIndices,
};
